/* eslint-disable @next/next/no-img-element */
/* eslint-disable @typescript-eslint/no-floating-promises */
/* eslint-disable @typescript-eslint/no-misused-promises */
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { useState } from "react";
import { api } from "../../src/utils/api";

import styles from "../styles/index.module.scss";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  const [email, setEmail] = useState("");

  const [user, setUser] = useState("");
  const changeName = api.user.changeName.useMutation();

  if (status == "authenticated") {
    console.log("chinese kaas eten nom nom nom");
    return (
      <>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <h1>Welkom {session.user.name}</h1>
          <button onClick={() => signOut()}>Log out</button><br />

          <input type="text" onChange={ (e) => {
            setUser(e.target.value);
          }} />
          <button onClick={ () => {
            changeName.mutate({ name: user });  
          }}>Submit</button>
        </main>
      </>
    );
  } 

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
        <div className={styles.flex}>
          <div className={styles.box}>
            <img src="/chillhub.png" alt="jpg" />

            <input type="text" placeholder="Email" onChange={ (e) => {
              setEmail(e.target.value);
            }} />
            <button className={styles.sign} onClick={ () => {
              signIn("email", { email: email}); 
            }}>Sign in</button>

            <button className={styles.discord} onClick={ () => {
              signIn("discord");
            }}><b>Log in met discord</b></button>
          </div>
        </div>

      </main>
    </>
  );
};

export default Home;
