/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import styles from "../styles/verify.module.scss";

const verifyRequest = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

                <div className={styles.flex}>
                    <div className={styles.box}>
                        <img src="/chillhub.png" alt="jpg" />

                        <div>
                            Er is een Mail naar u gestuurd om te kunnen inloggen.
                        </div>
                    </div>
                </div>

            </main>
        </>
    );
}

export default verifyRequest;